fix(github): 실패 잡 주석처리

diff --git a/.github/workflows/test-slack-pr.yml b/.github/workflows/test-slack-pr.yml
--- a/.github/workflows/test-slack-pr.yml
+++ b/.github/workflows/test-slack-pr.yml
@@ -20,14 +20,14 @@ jobs:
       - name: 성공하는 단계
         run: echo "This job always succeeds."
 
-  failure_job:
-    name: This job will fail
-    runs-on: ubuntu-latest
-    steps:
-      - name: 실패하는 단계
-        run: |
-          echo "This job is designed to fail."
-          exit 1
+  # failure_job:
+  #   name: This job will fail
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 실패하는 단계
+  #       run: |
+  #         echo "This job is designed to fail."
+  #         exit 1
 
   notify-on-completion:
     name: Notify Slack on Job Completion
